# 数据操作

## 2.1.1 入门

In [458]:
import torch

生成0到12的整数

In [459]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


显示x的形状

In [460]:
x.shape

torch.Size([12])

In [461]:
x.numel()

12

In [462]:
x.reshape(3,4)
# x.reshape(-1,4)
# x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

创建全零张量

In [463]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

创建全一张量

In [464]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

以下代码创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。

In [465]:
torch.randn(2,3)

tensor([[ 0.6230,  1.1792, -0.3142],
        [ 1.4554,  0.7520,  0.6942]])

用列表来创建张量

In [466]:
x = torch.tensor([[1.0,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## 2.1.2 运算符

对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。 我们可以在同一形状的任意两个张量上调用按元素操作。**为幂运算

In [467]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

对每个元素计算 以e为底x为指数的指数预算，例如e**2=7.3891


In [468]:
x = torch.exp(x)
x

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

两个张量连结  dim=0按列堆叠，dim=1按行堆叠

In [469]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(X.shape)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(Y.shape)
Z = torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
Z

torch.Size([3, 4])
torch.Size([3, 4])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

以X == Y为例： 对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1。 这意味着逻辑语句X == Y在该位置处为真，否则该位置为0。

In [470]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

张量中的元素求和

In [471]:
X.sum()

tensor(66.)

## 2.1.3 广播机制

由于a和b分别是
和
矩阵，如果让它们相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的
矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。


In [472]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

具体相加细节就是
a:[[0],[0],
   [1],[1],
   [2],[2]]
b:[[0,1],
   [0,1],
   [0,1]]


In [473]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 索引和切片

用[-1]选择最后一个元素,用[1:3]选择第二个和第三个元素

In [474]:
x = torch.arange(12).reshape((3, 4))
print(x)
print(x[-1])
x[1:3]


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 8,  9, 10, 11])


tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

## 2.1.5 numpy与张量之间的互相转化

In [475]:
x = torch.arange(12).reshape((3, 4))
print(x)
a= x.numpy()
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [476]:
x = torch.tensor([3.5])
print(x)
a = x.item()
print(a)

tensor([3.5000])
3.5


In [477]:
x= torch.arange(12).reshape((3, 4))
print(x)
print(x.tolist())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [478]:
import numpy as np
import torch

# 创建 NumPy 数组
arr = np.array([1, 2, 3])  # 例如：[1 2 3]

# 转换为张量
tensor = torch.from_numpy(arr)

print(tensor)  # 输出：tensor([1, 2, 3], dtype=torch.int64)

tensor([1, 2, 3], dtype=torch.int32)


In [479]:

import torch

# 创建张量（默认在 CPU 上）
tensor = torch.tensor([1, 2, 3])  # 输出：tensor([1, 2, 3])
print(tensor)
# 转换为 NumPy 数组
arr = tensor.numpy()

print(arr)  # 输出：[1 2 3]

tensor([1, 2, 3])
[1 2 3]
